run '~/.tmux/plugins/tpm/tpm' # Menajdor de paqeutes de tmux

# General config
# -----------------------------------------------------------------------------
set -g prefix ^A #Cambiar al tecla maestra de tmux
set -g set-clipboard on          # use system clipboard
setw -g mode-keys vi
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',xterm-256color:Tc'
set -g status-position top
set -g set-clipboard on          # use system clipboard

# Fix index
set -g base-index 1 # Los windows empiezan en 1
set -g pane-base-index 1 # Los paneles empiezan en 1
set -g renumber-windows on #Reenumera los windos cuando uno se cierra.


#Floating window (Alt + g)
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  # open in the same directory of the current pane
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

# Plugins
# -----------------------------------------------------------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @catppuccin_flavor 'mocha'
set -g @plugin 'christoomey/vim-tmux-navigator' # Tmux navigator like vim
set -g @plugin 'tmux-plugins/tmux-resurrect' #prefix + Ctrl-s - save; prefix + Ctrl-r - restore
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-continuum'

## Theme
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @ukiyo-theme "kanagawa/dragon"  # darker
set -g @kanagawa-plugins "git cpu-usage ram-usage time battery"
set -g @kanagawa-time-format "%R %F" # conf. clock
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-show-left-sep 
set -g @kanagawa-show-right-sep 


## Keymaps
# -----------------------------------------------------------------------------

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"
